targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: '3.38'
              modules:
                - json1
                - fts5
          apply_converters_on_variables: true
          store_date_time_values_as_text: true
          named_parameters: true
          generate_values_in_copy_with: true
          scoped_dart_components: true
