targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: '3.38'
              modules:
                - json1
                - fts5
          apply_converters_on_variables: true
          store_date_time_values_as_text: true
          named_parameters: true
          generate_values_in_copy_with: true
          scoped_dart_components: true

      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          output_format: single_file
          namespaces: false
          translate_var: t
          enum_name: AppLocale
          key_case: snake
          key_map_case: camel
          param_case: pascal
          string_interpolation: double_braces
