name: finlytics
description: Finlytics

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # General
  cupertino_icons: ^1.0.0
  collection: ^1.17.0
  equatable: ^2.0.5
  intl: ^0.18.0

  # Drift
  drift: ^2.8.1
  path_provider: ^2.0.13
  http: ^0.13.5
  sqlite3: ^1.9.3
  sqlite3_flutter_libs: ^0.5.15

  # Riverpod
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  path: ^1.8.2

  # Other
  async: ^2.10.0
  flutter_svg: ^2.0.5
  permission_handler: ^10.2.0
  json_annotation: ^4.8.1
  fl_chart: ^0.62.0
  file_picker: ^5.3.0
  share_plus: ^7.0.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  rxdart: ^0.27.7
  slang: ^3.18.1
  slang_flutter: ^3.18.0
  flex_color_scheme: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Generators:
  build_runner: ^2.3.3
  json_serializable: ^6.2.0
  riverpod_generator: ^2.1.3
  drift_dev: ^2.8.3
  slang_build_runner: ^3.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/avatars/
    - assets/icons/currency_flags/
    - assets/icons/page_states/
    - assets/icons/entertainment/
    - assets/icons/other/
    - assets/icons/money/
    - assets/icons/food/
    - assets/icons/medical/
    - assets/icons/transport/
    - assets/sql/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
